"""Add business_name and registration_number columns

Revision ID: da794a6f1a26
Revises: 
Create Date: 2024-06-13 10:42:01.222684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da794a6f1a26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('business_name', sa.String(), nullable=True))
    op.add_column('configurations', sa.Column('registration_number', sa.String(), nullable=True))
    op.add_column('configurations', sa.Column('extra_details', sa.JSON(), nullable=False))
    op.drop_column('configurations', 'requirements')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('requirements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('configurations', 'extra_details')
    op.drop_column('configurations', 'registration_number')
    op.drop_column('configurations', 'business_name')
    # ### end Alembic commands ###
